"""Persistence ports. All declarations are SDK-free and synchronously scoped to a UnitOfWork.

``DeliveryRepository`` contract (fail-closed ledger, plan §6):
every mutating method is ONE short conditional UPDATE, checks ``claim_token`` where
applicable and returns ``False`` when ``rowcount == 0`` (claim lost or row already
processed). No method performs network I/O; the caller commits before any send.
"""

from collections.abc import Sequence
from typing import Protocol, runtime_checkable

from vk_topic_bridge.application.dto.delivery import (
    DeliveryRecord,
    ReserveOutcome,
    ReserveRequest,
)
from vk_topic_bridge.application.dto.settings import BridgeSettingsState, ToggleKind
from vk_topic_bridge.domain.enums import SourceType
from vk_topic_bridge.domain.value_objects import TopicInfo


@runtime_checkable
class BridgeSettingsRepository(Protocol):
    """Access to the singleton ``bridge_settings`` row."""

    def get(self) -> BridgeSettingsState | None: ...
    def upsert_chat(self, chat_id: int, title: str | None) -> BridgeSettingsState: ...
    def set_messages_topic(self, topic_id: int | None) -> BridgeSettingsState: ...
    def set_wall_topic(self, topic_id: int | None) -> BridgeSettingsState: ...
    def set_toggle(self, kind: ToggleKind, value: bool) -> BridgeSettingsState: ...
    def reset(self) -> BridgeSettingsState: ...


@runtime_checkable
class TelegramTopicsRepository(Protocol):
    """Persistent view of discovered forum topics for the registered chat."""

    def replace_all(self, chat_id: int, topics: Sequence[TopicInfo]) -> None: ...
    def list(self, chat_id: int) -> list[TopicInfo]: ...
    def mark_missing(self, chat_id: int, seen_topic_ids: Sequence[int | None]) -> None: ...


@runtime_checkable
class VkAliasRepository(Protocol):
    """Per-VK-user aliases; at most one alias and one destination topic per user."""

    def list_for_user(self, vk_user_id: int) -> list[tuple[int | None, str]]: ...
    def upsert(
        self, vk_user_id: int, topic_id: int | None, alias: str, alias_normalized: str
    ) -> None: ...
    def delete(self, vk_user_id: int, topic_id: int | None) -> None: ...


@runtime_checkable
class DeliveryRepository(Protocol):
    """Atomic CAS ledger. See module docstring for claim/rowcount semantics."""

    def reserve(self, request: ReserveRequest) -> ReserveOutcome: ...
    def claim_reserved(self, delivery_id: int, claim_token: str, lease_seconds: int) -> bool: ...
    def mark_send_started(self, delivery_id: int, claim_token: str) -> bool: ...
    def mark_published(
        self, delivery_id: int, claim_token: str, message_ids: Sequence[int]
    ) -> bool: ...
    def mark_publication_ambiguous(
        self, delivery_id: int, claim_token: str, code: str | None, message: str | None
    ) -> bool: ...
    def mark_failed_before_send(
        self, delivery_id: int, claim_token: str, code: str | None, message: str | None
    ) -> bool: ...
    def mark_failed_permanent(
        self, delivery_id: int, claim_token: str, code: str | None, message: str | None
    ) -> bool: ...
    def claim_reaction(self, delivery_id: int) -> bool: ...
    def mark_reaction_succeeded(self, delivery_id: int) -> bool: ...
    def mark_reaction_failed(
        self, delivery_id: int, code: str | None, message: str | None
    ) -> bool: ...
    def get(self, source_type: SourceType, source_key: str) -> DeliveryRecord | None: ...
    def list_pending_reactions(self) -> list[DeliveryRecord]: ...
    def list_ambiguous(self) -> list[DeliveryRecord]: ...
